### ISSUE TITLE
Issue with Parcelable

### ISSUE THREAD

**Issue by ShubhGar** [arkivanov/Essenty#89] opened 2023-04-19 14:31 UTC
file:///Users/shubham.garg/Downloads/Android-SDK-Sample-App-main/payu-sdk/src/commonMain/kotlin/com/payu/india/Model/Bnpl.kt:9:6 Class 'Bnpl' is not abstract and does not implement abstract member public abstract fun describeContents(): Int defined in android.os.Parcelable

**Comment by arkivanov** [comment] 2023-04-19 14:37
Please make sure that you have applied the `kotlin-parcelize` Gradle plugin. See the [corresponding Readme section](https://arkivanov.github.io/MVIKotlin/).

**Comment by ShubhGar** [comment] 2023-04-19 15:50
yes, I follow all step mention in readme, do you have any sample app for same

**Comment by arkivanov** [comment] 2023-04-19 15:57
Sure, you can check this one - https://github.com/arkivanov/Decompose/blob/master/sample/shared/shared/build.gradle.kts

The error you mentioned means that the Android `Parcelable` interface is not implemented for that class. Which happens if `kotlin-parcelize` plugin is not applied.

**Comment by ShubhGar** [comment] 2023-04-19 16:05
<img width="895" alt="Screenshot 2023-04-19 at 9 35 03 PM" src="https://user-images.githubusercontent.com/24808854/233134671-0400736e-2123-4a5b-8f66-560605129897.png">
check this screenshot of my build.gradle.kts

**Comment by arkivanov** [comment] 2023-04-19 16:08
Could you please also show the `Bnpl` class?

**Comment by arkivanov** [comment] 2023-05-18 23:03
Closing this for now. Feel free to reopen if the issue is still relevant.

**Closed by arkivanov** 2023-05-18 23:03 UTC
Labels: question
