### ISSUE TITLE
Unable to get LifeCycle event for the KMP

### ISSUE THREAD

**Issue by himanshumistri** [arkivanov/Essenty#164] opened 2024-04-08 13:37 UTC
In Common code of Compose Multiplatform,

I have the below code.

     LaunchedEffect("LifeCycle"){
            val callbacks: Lifecycle.Callbacks =
                object : Lifecycle.Callbacks {
                    override fun onCreate() {

                    }

                    override fun onStart() {

                    }

                    override fun onResume() {

                    }

                    override fun onPause() {
                        Logger.i (messageString = "Home Screen LaunchedEffect onPause", tag = "Home")
                    }

                    override fun onStop() {
                        Logger.i (messageString = "Home Screen LaunchedEffect onStop", tag = "Home")
                    }

                    override fun onDestroy() {

                    }
                }

            viewModel.lifeCycleCallBack = callbacks
            mAppLifeCycleOwner.lifecycle.subscribe(callbacks)
            Logger.i (messageString = "Home Screen LaunchedEffect lifeCycleCallBack register", tag = "Home")
        } 

I does not trigger, I am testing it with Android for now, May be I am missing something...

I am also try below as well

`private var mlifecycle :LifecycleRegistry = LifecycleRegistry(initialState = Lifecycle.State.INITIALIZED)`

In my Android Native activity.

 ```
  override fun onStop() {
          super.onStop()
          mlifecycle.onStop()
          Logger.i (messageString = "onStop", tag = "MainActivity")
      }
```

**Comment by arkivanov** [comment] 2024-04-08 14:10
It would be nice if you could provide a complete reproducer, as the provided code is incomplete.

**Comment by himanshumistri** [comment] 2024-04-08 19:16
Here you go with my native main activity code of android : https://github.com/himanshumistri/KMPStarterKit/blob/main/androidApp/src/main/java/com/bumble/starter/MainActivity.kt

Here is my Compose Multiplatform Code where I need lifecycle event callback.

https://github.com/himanshumistri/KMPStarterKit/blob/main/shared/src/commonMain/kotlin/com/bumble/appyx/shared/child/ChildNode1.kt

I am not getting any event in ChildNode1

**Comment by arkivanov** [comment] 2024-04-09 10:51
I think your implementation has multiple issues. Here are some of them.

1. [AbcAppLifeCycle](https://github.com/himanshumistri/KMPStarterKit/blob/main/shared/src/commonMain/kotlin/com/bumble/appyx/shared/lifecycle/AbcAppLifeCycle.kt) implements `Lifecycle`, but the registered callbacks are never called.
2. I don't think that `AbcAppLifeCycle` gets somehow connected with the `LifecycleRegistry` defined in `MainActivity`.
3. In the `MainActivity` you are calling `essentyLifecycle()` but you are not using the returned `Lifecycle`. You could just use that instead of `LifecycleRegistry`.

Since you are using Appyx, I suggest reaching out to the developers and asking for help with lifecycle handling. Maybe there is an out-of-the box way. Or just use [Decompose](https://github.com/arkivanov/Decompose) for navigation.

**Comment by arkivanov** [comment] 2024-04-17 13:45
Closing this for now. Feel free to reopen if there are any questions or issues related to the Essenty library.

**Closed by arkivanov** 2024-04-17 13:45 UTC
