### ISSUE TITLE
Unresolved reference: Parcelize

### ISSUE THREAD

**Issue by DATL4G** [arkivanov/Essenty#79] opened 2022-12-25 12:12 UTC
The latest version (0.7.0) shows the Parcelize annotation red with this error message: "Unresolved reference: Parcelize" in IntelliJ Ultimate 2022.3.1

**This is NOT urgent** as the project builds fine, just a little annoying.

Version 0.6.0 doesn't have this problem.

**Comment by arkivanov** [comment] 2022-12-25 12:54
That might be an issue with IDEA. You can try deleting the `.idea` folder and reopening the project, and see if this helps. Also what Kotlin version you are using? Can you try Kotlin 1.7.21? Do you have a reproducer project?

**Comment by arkivanov** [comment] 2022-12-25 13:07
I have just checked, it works just fine for me:

- IntelliJ IDEA 2022.3.1 (Ultimate Edition)
- Kotlin `1.7.20`
- Kotlin IntelliJ IDEA plugin `223-1.7.21-release-272-IJ8214.52`

**Comment by DATL4G** [comment] 2022-12-25 13:07
I tried deleting the ```.idea``` folder but that didn't help.
I'm using Kotlin version 1.7.22

I don't really have a reproducer project, but this is the [project](https://github.com/DATL4G/BurningSeries-Android/tree/compose) I'm facing this issue. (compose branch)
It's not that small so for explanation:

- model module depends on essenty
- model api's essenty to other modules like app module
- 
Example class having this issue [```dev.datlag.burningseries.ui.screen.home.HomeScreenComponent```](https://github.com/DATL4G/BurningSeries-Android/blob/compose/app/src/commonMain/kotlin/dev/datlag/burningseries/ui/screen/home/HomeScreenComponent.kt)

**Comment by arkivanov** [comment] 2022-12-25 13:26
Thanks! Looks like it was broken in #73. `Parcelize` annotation was marked as `@OptionalExpectation` and removed from all non-Android targets. Since you are using only `android` and `jvm` targets, it resolves to the `jvm` artifact (not common) which doesn't have `Parcelize` anymore. I will revert this particular change.

**Comment by arkivanov** [comment] 2022-12-25 13:29
I think this happens because Kotlin commonizer doesn't support sharing `android` and `jvm` source sets yet. So it defaults to just `jvm`.

**Comment by arkivanov** [comment] 2022-12-25 13:31
Looks like we can't use `@OptionalExpectation` at all, I will avoid it completely for now.

Cc: @sellmair

**Closed** 2022-12-25 15:34 UTC
Labels: bug

**Comment by arkivanov** [comment] 2022-12-25 15:55
Version `0.7.1` is released and should fix this issue. Please allow ~2 hours for artifacts to fully propagate.

**Comment by DATL4G** [comment] 2022-12-25 16:23
Works like a charm, btw I just check the artifact availability here https://repo1.maven.org/maven2/com/arkivanov/essenty/parcelable/

**Comment by arkivanov** [comment] 2022-12-25 16:26
Yeah, it's often faster than 2 hours. But there are more target-specific artifacts, they are synchronized in batches, so some targets may be still missing. https://repo1.maven.org/maven2/com/arkivanov/essenty/

**Comment by MaxElkin** [comment] 2023-05-02 18:03
The issue can still be reproduced on latest version 1.1.0 for **nested** classes.

**Comment by arkivanov** [comment] 2023-05-02 18:11
Can you share a reproducer?
